import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { useWallet } from "@/hooks/useWallet";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const { walletAddress, connectWallet } = useWallet();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {walletAddress ? (
          <div className="flex flex-col items-center justify-center h-screen bg-gray-900 text-white">
            <div className="flex flex-col items-center gap-4">
              <img
                src="studchain-logo.svg"
                alt="StudChain Logo"
                className="w-24 h-24"
              />
              <h1 className="text-xl font-medium">StudChain</h1>
              <p className="text-sm text-gray-400">Какой-то текст описание платформы</p>
            </div>
            <div className="absolute bottom-6 w-full px-6">
              <button className="w-full bg-white text-black py-3 rounded-lg text-center text-lg font-medium" onClick={connectWallet}>
                Connect Wallet
              </button>
            </div>
          </div>
        ) : 
        children
      }
      </body>
    </html>
  );
}
